"""Constants for DOEMS."""

from __future__ import annotations

DOMAIN = "doems"
NAME = "DOEMS"
VERSION = "0.1.0-alpha.2"

CONF_INSTANCE_NAME = "instance_name"
DEFAULT_INSTANCE_NAME = NAME

CONF_ENERGY_FORECAST_ENABLED = "energy_forecast_enabled"
CONF_ENERGY_SOURCE_MODE = "energy_source_mode"
CONF_ENERGY_START_PROFILE = "energy_start_profile"
CONF_HOME_POWER_ENTITY = "home_power_entity"
CONF_GRID_NET_POWER_ENTITY = "grid_net_power_entity"
CONF_GRID_SIGN_CONVENTION = "grid_sign_convention"
CONF_SOLAR_POWER_ENTITY = "solar_power_entity"
CONF_BATTERY_PRESENT = "battery_present"
CONF_BATTERY_CHARGE_POWER_ENTITY = "battery_charge_power_entity"
CONF_BATTERY_DISCHARGE_POWER_ENTITY = "battery_discharge_power_entity"

ENERGY_SOURCE_DIRECT = "direct_home_power"
ENERGY_SOURCE_BALANCE = "power_balance"
ENERGY_SOURCE_MODES = [ENERGY_SOURCE_DIRECT, ENERGY_SOURCE_BALANCE]

GRID_SIGN_POSITIVE_IMPORT = "positive_import_negative_export"
GRID_SIGN_POSITIVE_EXPORT = "positive_export_negative_import"
GRID_SIGN_OPTIONS = [GRID_SIGN_POSITIVE_IMPORT, GRID_SIGN_POSITIVE_EXPORT]

PROFILE_CONTRACT_VERSION = 1
PROFILE_NORMAL = "normal"
PROFILE_AWAY = "away"
PROFILE_UNCLASSIFIED = "unclassified"
PROFILE_MIXED = "mixed"
PROFILE_LEARNING_OPTIONS = [PROFILE_NORMAL, PROFILE_AWAY]
PROFILE_OPTIONS = [PROFILE_NORMAL, PROFILE_AWAY, PROFILE_UNCLASSIFIED]

QUARTER_MINUTES = 15
QUARTER_SECONDS = QUARTER_MINUTES * 60
QUARTERS_PER_DAY = 96
FORECAST_HORIZON_HOURS = 72
FORECAST_SLOTS = FORECAST_HORIZON_HOURS * 60 // QUARTER_MINUTES
RECENCY_HALF_LIFE_DAYS = 28.0
MAX_HISTORY_DAYS = 400
MIN_VALID_COVERAGE = 0.90

STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}.energy_forecast"
ENERGY_STORE_SCHEMA_VERSION = 1

PLATFORMS = ["sensor", "select"]
DEVICE_IDENTIFIER = "main"
FOUNDATION_PHASE = "p2_1_energy_forecast"
CANONICAL_HOME_POWER_ENTITY = "sensor.doems_source_home_power"

PUBLIC_OBJECT_ID_PREFIX = "doems_"
