"""Frozen Alpha76 constants retained for parity defaults only."""
DOMAIN = "doems"
PLAN_SLOT_COUNT = 3
DEFAULT_AUTO_EXECUTION_BUFFER_PERCENT = 2.0
DEFAULT_BATTERY_CAPACITY_KWH = 7.2
DEFAULT_CHARGE_EFFICIENCY_PERCENT = 92.0
DEFAULT_DISCHARGE_EFFICIENCY_PERCENT = 92.0
MIN_ACTIONABLE_SAFETY_CHARGE_KWH = 0.10
MIN_SOC_PERCENT = 5
